### ISSUE TITLE
oauth doesn't work (weetweet will not load)

### ISSUE THREAD

**Issue by jpmenil** [DarkDefender/weetweet#2]
Hi,

it seems i can't get weetweet working:

python: script "weetweet" chargé, version 1.1 (Weechat twitter client)
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jean-philippe/.weechat/python/weetweet.py", line 951, in oauth_proc_cb
python: stdout/stderr:     oauth_token, oauth_token_secret = parse_oauth_tokens(out)
python: stdout/stderr:   File "/home/jean-philippe/.weechat/python/weetweet.py", line 922, in parse_oauth_tokens
python: stdout/stderr:     k, v = r.split('=')
python: stdout/stderr: ValueError: need more than 1 value to unpack
python: erreur dans la fonction "oauth_proc_cb"

on debian or gentoo with python3.

Is it a know issue?

Regards

**Comment by djbclark** [comment]
I had this problem too. The solution was the same as for someone else: install twitter lib to python3 as well as python2. My added confusion (that perhaps someone else can be spared) was that I didn't realize weechat supported using both python versions at the same time; I actually installed pybuffer.py to see which interpreter binary weechat was using (more complex in my case due to local and system level installs), and the python2 popped up, so I installed twitter to python2 wrongly thinking weetweet had to be using the same interpreter. Anyway, thanks for the awesome software!

**Comment by DarkDefender** [comment]
@djbclark well technically, weechat doesn't support using both at the same time. The default is that it runs python2. However it seems like they will migrate to python3 soonish.

Because I need to make sure that all calls done to the twitter API doesn't lock up/block weechat, I had to spawn new processes that does this and returns the result to weechat when it's done.
I spawn all these processes as python3 because I wanted to simplify the code and to make it easier to bug test. There are also some python3 only features that I use and didn't want to backport to python2 :p

I'm glad you like it!
If you have any suggestions and/or find some bugs, please report them here.

**Comment by bronzehedwick** [comment]
For anyone experiencing this issue on Ubuntu, I was able to solve by installing `pip3` with `sudo apt-get install python3-pip`, then installing the lib. with `sudo pip3 install twitter`.

**Comment by jpmenil** [comment]
hey @DarkDefender , i guess we can close this one :)
