### ISSUE TITLE
Script not up to date (on weechat repo)

### ISSUE THREAD

**Issue by jpmenil** [DarkDefender/weetweet#23]
Hey @DarkDefender,

seem that the following commit 68cca7c17341e8f5d90e74ecba1dad4078888442
is not present in the weechat master branch.
Took me a few instants to understand why my stream suddenly become so heratic since few days ... :)

Dunno the process on how to ask weechat dev to update, maybe you can help?
Seem that you maybe need to bump the version too.

Best regards,

**Comment by DarkDefender** [comment]
Yes you are right, I should have updated it long ago. The reason I haven't pushed it upsteam yet is that there is currently a bug that I run into sometime when I start weetweet (the initial `:new` command fails, the others after it works nicely).

However I haven't really had time to hunt down this bug so nothing has really happened on that front. I guess it's better to just bump the version and get it merged upstream so that it now atleast works after twitter has removed streams.

**Comment by DarkDefender** [comment]
Here you go. Now we just have to wait for it to get merged: https://github.com/weechat/scripts/pull/284

**Comment by jpmenil** [comment]
Perfect!

Many thanks!!

**Comment by DarkDefender** [comment]
The changes are now finally live in the main repo
